[package]
name = "pi-whim-gpui"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
gpui.workspace = true
gpui-component.workspace = true
pi-whim-core = { path = "../pi-whim-core" }
pi-whim-engine = { path = "../pi-whim-engine" }
pi-whim-theme = { path = "../pi-whim-theme" }

[dev-dependencies]
uuid.workspace = true
gpui_platform.workspace = true
gpui-component-assets.workspace = true
