name: Check

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/setup-node@v4
        with:
          node-version: 22.19.0
      - run: cargo fmt --check
      - run: cargo test --workspace
      - run: cargo clippy --workspace --all-targets -- -D warnings
